# This file was *autogenerated* from the file optim.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
var('p1,p2,n1,n2,n')
__tmp__=var("n"); fac = symbolic_expression(gamma(n+_sage_const_1 )).function(n)
__tmp__=var("n,m"); binom = symbolic_expression(fac(n) / fac(m) / fac(n-m)).function(n,m)
p = fac(n) / fac(n1) / fac(n2) / fac(n-n1-n2) * p1 * p2 * (_sage_const_1  -p1-p2)**(n-_sage_const_2 )
df = diff(p, n)
print solve(df, n)

p = n * p1 * (_sage_const_1 -p1) **(n-_sage_const_1 )
df = diff(p, n)
print solve(df, n)
