
from savitzky_golay import SGIntegrator
from assymetric_gauss  import AsymmetricGaussIntegrator
from trapez import TrapezIntegrator, TrapezIntegratorWithBaseline
from simplified_emg import SimplifiedEMGIntegrator
from no_integration import NoIntegration
from max_integrator import MaxIntegrator

